server:
  port: 8888

spring:
  application:
    name: configuration-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DimeVision/microservices-config-server.git
          username:
          password:
          clone-on-start: true
          force-pull: true
