server:
  port: 8080

spring:
  application:
    name: customer

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5444/Student
    username: dimevision
    password: Admin15913371Fommkaa31
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true