server:
  port: 8080

spring:
  application:
    name: customer

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://
    username: 
    password: 
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
